Hasty attempt at idempotency

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -14,8 +14,8 @@ cd "$(dirname "$0")"
 find -L "." -mindepth 2 -type f -executable ! -name "*##*" ! -name "#*" \
         | sort | while IFS= read -r SCRIPT; do
     echo "Running $SCRIPT"
-    # if ! "$SCRIPT"; then
-    #     echo "Error: bootstrap '$SCRIPT' failed" >&2
-    #     exit 1
-    # fi
+    if ! "$SCRIPT"; then
+        echo "Error: bootstrap '$SCRIPT' failed" >&2
+        exit 1
+    fi
 done
